# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


CarBrand.create([{name: 'Toyota'}, 
							{name: 'Honda'}, 
							{name: 'Acura'}, 
							{name: 'Alfa Romeo'}, 
							{name: 'Aston Martin'}, 
							{name: 'Audi'}, 
							{name: 'Bentley'}, 
							{name: 'BMW'}, 
							{name: 'Bugatti'}, 
							{name: 'Buick'}, 
							{name: 'Cadillac'}, 
							{name: 'Chevrolet'}	, 
							{name: 'Chrysler'}, 
							{name: 'Citrogen'}, 
							{name: 'Dodge'}, 
							{name: 'Ferrari'},
							{name: 'Fiat'}, 
							{name: 'Ford'},
							{name: 'Geely'}, 
							{name: 'General Motors'}, 
							{name: 'GMC'}, 
							{name: 'Hyundai'}, 
							{name: 'Inifiniti'} , 
							{name: 'Jaguar'}, 
							{name: 'Jeep'}, 
							{name: 'Kia Motors'}, 
							{name: 'Koenigsegg'}, 
							{name: 'Land Rover'},
							{name: 'Lexus'},
							{name: 'Maserati'},
							{name: 'McLaren'},
							{name: 'Mercedes-Benz'},
							{name: 'Mini'},
							{name: 'Mitsubishi'},
							{name: 'Nissan'},
							{name: 'Pigani'},
							{name: 'Peugeot'},
							{name: 'Porsche'},
							{name: 'Ram'},
							{name: 'Renault'},
							{name: 'Rolls Royce'},
							{name: 'Saab'},
							{name: 'Subaru'},
							{name: 'Suzuki'},
							{name: 'Tata Motors'},
							{name: 'Tesla'},
							{name: 'Volskwagen'},
							{name: 'Volvo'} ])